server:
  port: 8081

logging:
  level:
    root: info
    com.hyomee: debug


spring:
  h2:
    console:
      enabled: true
      path: /hyomee

  # 드라이버 위치 : C:\Users\ASUS\.m2\repository\com\h2database\h2\2.1.214
  datasource:
    ## url: jdbc:h2:mem:hyomee # 인메모리 db
    url : jdbc:h2:file:/data/hyomee # 파일 방식
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # create: 기존 테이블을 삭제하고 새로 생성(DROP + CREATE)
      # create-drop: CREATE 속성에 추가로 애플리케이션을 종료할 때 생성한 DDL을 제거 (DROP + CREATE + DROP)
      # update: DB 테이블과 엔티티 매핑 정보를 비교해서 변경 사항만 수정
      # validate: DB 테이블과 엔티티 매핑정보를 비교해서 차이가 있으면 경고를 남기고 애플리케이션을 실행하지 않음. DDL을 수행하지 않음
      # none: 자동 생성 기능을 사용하지 않음
      ## 개발 초기 단계는 create 또는 update
      ## 초기화 상태로 자동화된 테스트를 진행하는 개발자 환경과 CI서버는 create 또는 create-drop
      ## 테스트 서버는 update 또는 validate
      ## 스테이징과 운영 서버는 validate 또는 none
      ddl-auto: update
      database-platform : org.hibernate.dialec.tH2Dialect
      defer-datasource-initialization: true
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy # 대문자 생성
    properties:
      hibernate:
        format_sql: true # ???? query? ???


logging.level:
  org.hibernate.SQL: debug